<template>
  <div class="h5-content">
    <div class="title">Terms of Service</div>
    Please read the terms and conditions of the privacy policy before registering on this platform or before receiving the material or information through this platform. We may change or revise the terms of use without notice. It is good to refer to the legend of final renewal. Please confirm the change of the terms of use periodically on your own responsibility. Therefore, when you access or use this platform, please check this agreement. After the change of this agreement, if you are using this platform, you are deemed to have been agreed to the terms of the change.
    <br />
    <br />
    This document is an electronic record of documents, agreements and contracts generated by electronic digital systems, and does not require digital signatures or physical signatures required by the 2000 information technology act. This book is issued in accordance with Article 3 of the information technology act.
    <br />
    <br />

    If you use this app or register any information, the user (hereinafter referred to as "customer") is deemed to have agreed to this agreement. The terms and conditions of this agreement, along with disclaimer and privacy policy, describe the guidelines, rules, policies and conditions underlying our relationship with our clients. If you do not agree with the terms of use and privacy policy, you will not be able to use paisago products, software, services or mobile applications. Paisago financial has the right to change or modify this Convention at any time without prior notice, with its own discretion. By using or continuing to use a mobile application, you will be deemed to have accepted or revised the terms and conditions. Ownership
    <br />
    <br />
    You agree and accept and agree that paisago financial has the rights, interests, and interests of this service, including intellectual property rights (regardless of registration). You also agree that the service may contain information that the paisago finance is considered confidential and does not disclose such information without any prior written consent of paisiago finance in any circumstances. With regard to mobile applications, paisago financial gives customers a limited license for mobile applications and services and for personal use. This license does not give you the right to copy, download, modify, reverse engineering, parody, reverse assemble, find, transfer, sell, set security, sublicense, and transfer your source code. You are not responsible for the use of paisago's trademark, trade name, logo, domain name, service mark, and other proprietary. You shall not have the right to obscure, delete, or alter the ownership of the ownership of the service (including copyright and trademark) that may or may not be included in this service. You shall not have the right to imitate or transfer this service. Disclaimer of warranty. Services and content available on this
    mobile application and this mobile application are provided in the "state" and "available" state. PAYGO finance does not guarantee any implied or explicit warranty. However, this is not limited to the implied warranties of titles, non infringement, merchandise, security and accuracy, conformity to a particular purpose and any warranty arising from commercial use, the course or method of paisago finance guarantees and denies. (1) content is accurate, up-to-date, complete, or related to your situation. (2) the mobile application is available in a way that meets the user's requirements or is timely, safe, error free, and interrupted (3) products and information obtained through mobile applications The quality of services or other materials satisfies the user's expectations (4) the results or services provided through the mobile application are reliable or accurate. Limitation of liability
    <br />
    <br />

    Paisago financial and its directors, employees, affiliates, agents, employees, suppliers, in any case, (1) any loss, death, injury, accident, natural disaster, claim, delay or special, direct, indirect, punitive It shall not be liable for any derivative or incidental damages (including but not limited to this). (a) delay or failure (including the use or limitation of any element in a mobile application) (b) the use of content or mobile applications (c) the default or inappropriate performance by the provider or by us Even if we have damaged the site or mobile device as a result of our access to mobile applications or as a result of downloading mobile application content or other assets, even if we recognised the virus that could trigger the property.

    <br />
    <br />
    Declaration of liability This mobile application and the services and content provided by the mobile application are provided on an "as is" and "as available" basis. paisaGo Financial disclaims all warranties, whether express or implied. However, this is not limited to implied warranties of title, non-infringement, merchantability, safety and accuracy, fitness for a particular purpose, and any warranties arising from commercial use, performance or trade. paisaGo Financial makes no warranties and excludes all obligations (1) The Content will be comprehensive, accurate, up-to-date, complete or even relevant to your situation. (2) The mobile application meets your needs or will be available on time, safely, error-free and uninterrupted. (3) The quality of products, information, services or other materials from the mobile application meets your expectations. (4) The results obtained through the mobile application or the services provided by the mobile application will be reliable or accurate.
    <br />
    <br />
    Limitation of liability PaisaGo Financial and its directors, employees, subsidiaries, agents, officers and suppliers shall under no circumstances be liable (1) for any loss, death, injury, accident, natural disaster, claim, delay or special, exemplary, direct, indirect, punitive, consequential or accidental damage (including loss of savings or loss of profits). loss), whether based on tort, contract or strict liability arising out of or in connection with: (a) delay or error in any part of the Mobile App (including inability or limitation of use); (b) any use of the Content or Mobile App; (c) Service Provider or our defective or improper performance, even if we are aware of the possibility of damage to the parties or viruses that may occur to the Mobile Device or other property as a result of accessing the Mobile App or downloading Content from the Mobile App.
    <br />
    <br />
    The Mobile App reserves the right to provide links or links to third-party mobile websites/apps. However, PaisaGo Financial has no particular control over third party applications/websites and you acknowledge and agree that PaisaGo Financial is not responsible for and does not endorse in any way the content, products, advertisements or other materials. You further agree and acknowledge that PaisaGo Financial will not be liable for any damage caused or alleged to be caused by the use of or connection to any goods, services or content provided by any third party mobile application/website.
    <br />
    <br />
    Damage You acknowledge and agree to indemnify and hold harmless PaisaGo Financial and its directors, officers, employees and agents from and against all claims, demands, recovery, actions, damages, penalties, damages, fines or other fees or costs, including reasonable attorneys' fees, or resulting from a violation of the Terms (including a violation of law, third-party rights, privacy policy or use of the mobile application). implementation). Use the mobile application
    <br />
    <br />
    The mobile application is not for commercial or personal use. To be a user of the Mobile App, you must be at least 18 years old and able to enter into a binding contract. You are solely responsible for keeping your login details and password confidential. You are responsible for the use of the Mobile App by yourself or by any other person using your login information and password (with or without your permission). You agree to provide complete, clear, accurate and true information about yourself as required by the Mobile App. If you provide false, incomplete, outdated or misleading information, or if such information becomes false, incomplete, outdated or misleading, or if PaisaGo Financial has reasonable grounds to believe that such information is untrue, incomplete, inaccurate or outdated, PaisaGo Financial reserves the right to suspend your account, and refuse any further or future use of the Mobile App. Application. By providing Personal Data, you agree that you are interested in a particular service of the Mobile App and that you wish to purchase that service. You hereby consent to PaisaGo Financial contacting you by phone or electronic means in order to complete or
    fulfill your request. You clearly understand that using the Mobile App
    <br />
    <br />
    We are responsible for searching for loans and other financial products provided by mobile applications and applying only mobile applications for purposes purposes. You shall not be involved in a deceptive act or use this mobile application. You agree that you do not use mobile applications for illegal or prohibited or illegal purposes under local laws and conditions. We reserve the right to terminate, stop or restrict access to the components of the mobile application without notice. Additional conditions
    <br />
    <br />
    Paisago financial is not limited to, including, including, but not limited to, changes or declines, errors, inaccuracies, ambiguities, the scope and nature of services and other services, market practices, corporate reorganization, process changes, and customer requirements; Reserves the right to change mobile apps and websites TOS anytime. When a change occurs, paisago financial updates the terms on the mobile application or website.
    <br />
    <br />
    Paisago financial reserves the right to suspend or suspend services or incidental services temporarily or permanently to provide a notification period in order to maintain privacy and security, unless it is small changes to specific functions / content. Paisago financial is not liable for any change or suspension of services.
    <br />
    <br />
    You agree that you do not send any material or content that is deemed to be used for illegal or defamatory, harassment, abuse, obscene, threatening, privacy violations or illegal purposes.
  </div>
</template>

<style lang="scss" scoped>
.title {
  font-size: 20px;
  font-weight: bold;
  text-align: center;
  margin-bottom: 40px;
  color: #333;
}
.h5-content {
  padding: 20px;
  background: #fff;
  font-size: 12px;
  font-weight: 400;
  color: #999999;
  line-height: 16px;
  word-break: break-word;

  .head {
    font-size: 13px;
    color: #333;
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 30px;
  }
  strong {
    font-weight: bold !important;
    color: #333;
  }
}
</style>
